on:
  push:
    branches: [main]
    paths:
      - "packages/catppuccin-vsc/src/theme/**/*.ts"
      - "packages/catppuccin-vsc-storybook/**/*"
  pull_request:
    paths:
      - "packages/catppuccin-vsc/src/theme/**/*.ts"
      - "packages/catppuccin-vsc-storybook/**/*"

name: "Chromatic"

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm i --frozen-lockfile

      - name: Publish to Chromatic
        uses: chromaui/action@4ffe736a2a8262ea28067ff05a13b635ba31ec05 # v13
        with:
          buildScriptName: storybook:build
          exitOnceUploaded: true
          projectToken: chpt_e3cba49738d7554
          workingDir: packages/catppuccin-vsc-storybook
